Q 175.......
Select firstName,lastName,city,state from Person left join Address on Person.personId = Address.personId;
Q 181.......
select e1.name as Employee from Employee as e1 left join Employee as e2 on e1.managerId = e2.id where e1.salary > e2.salary;
Q 182.......
select email as Email from Person group by email having count(email)>1;
Q 183......
select c.name as Customers from Customers c where c.id not in (select c.id from Customers c inner join Orders o on c.id=o.customerId);
Q 577......
select e.name,b.bonus from Employee  as e left join Bonus as b on e.empId = b.empId
where b.bonus<1000 or b.bonus is null;
Q 584......
select name from Customer where referee_id <> 2 or referee_id is null ;
Q 586......
with cte as
(select customer_number,count(order_number) as c from Orders group by customer_number)
select customer_number from cte 
where c = (select max(c) from cte);
Q 595.....
select name,population,area from World where area >=3000000 or population >=25000000;
Q 596.....
select class from Courses group by class having count(student) >=5;
Q 610.....
select * ,
case 
  when x+y>z and y+z>x and x+z>y then "Yes"
  else "No"
end as Triangle
from Triangle;
Q 619....
with cte as
(select num from MyNumbers group by num having count(num) = 1 order by num desc)
select case when count(num)>0 then num else null end as num from cte limit 1;
Q 620....
select * from Cinema where id%2 <> 0 and description <> "boring" order by rating desc;
Q 627....
update Salary
set sex=case when sex = "f" then "m"
when sex = "m" then "f" end;
Q 1050...
select actor_id,director_id from ActorDirector group by director_id,actor_id having count(timestamp) >= 3; 

