Q 175.......
Select firstName,lastName,city,state from Person left join Address on Person.personId = Address.personId;
Q 181.......
select e1.name as Employee from Employee as e1 left join Employee as e2 on e1.managerId = e2.id where e1.salary > e2.salary;
Q 182.......
select email as Email from Person group by email having count(email)>1;
Q 183......
select c.name as Customers from Customers c where c.id not in (select c.id from Customers c inner join Orders o on c.id=o.customerId);