Q 175.......
Select firstName,lastName,city,state from Person left join Address on Person.personId = Address.personId;
Q 181.......
select e1.name as Employee from Employee as e1 left join Employee as e2 on e1.managerId = e2.id where e1.salary > e2.salary  ;